# Generated by Django 3.1 on 2020-08-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.CharField(max_length=10000, verbose_name='记事id')),
                ('operation', models.CharField(choices=[('A', 'Add'), ('E', 'Edit'), ('D', 'Delete'), ('F', 'Finish'), ('R', 'Recover')], max_length=1, verbose_name='操作')),
                ('record_time', models.DateTimeField(verbose_name='记录时间')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='标题')),
                ('text', models.TextField(max_length=20, verbose_name='内容')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('grade', models.CharField(choices=[('I', 'Important'), ('C', 'Common'), ('N', 'Necessary')], default='C', max_length=1, verbose_name='等级')),
                ('status', models.CharField(choices=[('U', 'Underway'), ('F', 'Finish'), ('D', 'Deleted'), ('O', 'Overtime'), ('P', 'Plan')], default='U', max_length=1, verbose_name='状态')),
            ],
        ),
    ]
