# Generated by Django 3.1 on 2020-08-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_id', models.CharField(max_length=10000, verbose_name='记事id')),
                ('operation', models.CharField(choices=[('A', 'Add'), ('E', 'Edit'), ('D', 'Delete'), ('F', 'Finish'), ('R', 'Recover')], max_length=1, verbose_name='操作')),
                ('r_time', models.DateTimeField(verbose_name='记录时间')),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='e_time',
            field=models.DateTimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(max_length=5, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='note',
            name='s_time',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('U', 'Underway'), ('F', 'Finish'), ('D', 'Deleted'), ('O', 'Overtime'), ('P', 'Plan')], default='U', max_length=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(max_length=20, verbose_name='内容'),
        ),
    ]
