# Generated by Django 3.1 on 2020-08-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(help_text='请输入记事标题', max_length=5, verbose_name='标题'),
        ),
    ]
