# Generated by Django 3.1 on 2020-08-24 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='name',
            new_name='title',
        ),
    ]
