# Generated by Django 3.1 on 2020-08-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200823_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='grade',
            field=models.CharField(choices=[('I', 'Important'), ('C', 'Common'), ('N', 'Necessary')], default='C', max_length=1, verbose_name='等级'),
        ),
    ]
